services:
  - type: web
    name: cinebee
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
